config/routes.rb
Rails.application.routes.draw do

  get 'profile/edit'

  get 'profile/update'

  get 'drones/search', to: 'drones#search'


  resources :drones do
    resources :rentals, only: [ :new, :create ]
  end

  resources :rentals, only: [:destroy, :show]

  get 'dashboard', to: 'pages#dashboard'

  get 'myrentals', to: 'pages#myrentals'


  resources :profile, only: [ :edit, :update ]

  mount Attachinary::Engine => "/attachinary"

  # get 'profile/edit', to: 'profile#edit'

  # patch 'profile/update', to: 'profile#update'

  # get 'rentals/index'

  # get 'rentals/show'

  # get 'rentals/destroy'


  devise_for :users, :controllers => { registrations:  "users/registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :drone
  before_validation :totalprice

  def totalprice
    self.total_price = ((end_date - start_date) * drone.daily_price)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def index
    @rentals = Rental.all
  end

  def show
    @rental = Rental.find(params[:id])
    @drone = Drone.find(@rental.drone_id)
  end

  def destroy
    @rental = Rental.find(params[:id])
    @rental.destroy

    redirect_to dashboard_path
  end

  def create
    @rental = Rental.new(params_rental_create)
    @rental.drone = Drone.find(params[:drone_id])
    @rental.user = current_user
      if @rental.save
        redirect_to dashboard_path, notice: "OK, drone booked for a total price of #{@rental.total_price} €"
      else
        render "rentals/new", notice: "Wrong booking not made"
      end
  end

  def new
    @rental = Rental.new(params_rental)
    @drone = Drone.find(params[:drone_id])
  end

  def params_rental
    params.require(:rental).permit(:end_date, :start_date)
  end

  private
  def params_rental_create
    params.require(:rental).permit(:end_date, :start_date)
  end

end

app/views/rentals/create.html.erb
<h1>Rentals#create</h1>

app/views/rentals/destroy.html.erb
<h1>Rentals#destroy</h1>
<p>Find me in app/views/rentals/destroy.html.erb</p>

app/views/rentals/index.html.erb
<h1>Rentals#index</h1>
<p>Find me in app/views/rentals/index.html.erb</p>

app/views/rentals/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4">

      <%= simple_form_for [@drone,@rental], url: drone_rentals_path do |f| %>
      <%= f.error_notification %>
      <%= f.input :start_date, required: true, autofocus: true %>
      <%= f.input :end_date, required: true, autofocus: true %>

      <%= f.submit "Book it now", class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/rentals/show.html.erb
<!-- # creation d'une vue de rental bootstrappée-->
<div class="show-wrapper" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_url "home.jpg" %>');">
</div>
<div class="container">

  <div class="row">

    <% card_background_image = %>
    <% if @drone.photo_drone? %>
    <% cl_image_path @drone.photo_drone.path, height: 800, width: 700, crop: :fill %>
    <% else %>
    <% image_path("https://static.pexels.com/photos/442587/pexels-photo-442587.jpeg") %>
    <% end %>

    <div class="col-xs-12 col-sm-6">

      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= card_background_image %>')">
        <div class="card-description">
          <h3><%= @drone.user.first_name %>'s drone </h3>
          <ul>
            <h4>It's a wonderfull <% @drone.brand %> </h4>
            <li> Price Day/Week/month : <% @drone.daily_price %>€ / <% @drone.weekly_deal %>€ / <% @drone.monthly_deal %>€ </li>
            <li> Model : <% @drone.model %></li>
            <li> Range : <% @drone.range %></li>
            <li> Time Flight : <% @drone.autonomy %> min</li>
            <li> Number of batteries : Rent with <% @drone.battery %> batteries</li>
            <li> Need of controller : <% @drone.controller ? "Yes" : "No" %></li>
            <li> Deposit : <% @drone.deposit %></li>
            <li> What's amazing about this drone : <% @drone.description %></li>
          </ul>
        </div>
      </div>
    </div>
  <!-- # Etat de reservation -->
  <div class="col-xs-12 col-sm-6">
    <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_url "home.jpg" %>');">
      <div class="card-category">Your rental</div>
      <div class="card-description">
        <h3>You booked <%= @drone.user.first_name %>'s drone</h3>
        <ul>
          <h4>It's a wonderfull <% @drone.brand %> </h4>
          <li> You booked it from <%= @rental.start_date %> to <%= @rental.end_date %></li>
          <li> Total is <%= @rental.total_price %> %></li>
        </ul>
      </div>
    </div>

  </div>

</div>
</div>

<%= link_to "Return to your rentals", myrentals_path %>