config/routes.rb
Rails.application.routes.draw do

  get 'profile/edit'

  get 'profile/update'

  get 'drones/search', to: 'drones#search'


  resources :drones do
    resources :rentals, only: [ :new, :create ]
  end

  resources :rentals, only: [:destroy, :show]

  get 'dashboard', to: 'pages#dashboard'

  get 'myrentals', to: 'pages#myrentals'


  resources :profile, only: [ :edit, :update ]

  mount Attachinary::Engine => "/attachinary"

  # get 'profile/edit', to: 'profile#edit'

  # patch 'profile/update', to: 'profile#update'

  # get 'rentals/index'

  # get 'rentals/show'

  # get 'rentals/destroy'


  devise_for :users, :controllers => { registrations:  "users/registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/dashboard.html.erb
<div class="dashboard-container">
  <div class="tabs1">
    <a class="tab1 active">
      <h3>My drones</h3>
    </a>
    <a class="tab1" href="<%= myrentals_path %>">
      <h3>My rentals</h3>
    </a>
    <a class="tab1" href="<%= profile_edit_path %>">
      <h3>My account</h3>
    </a>
  </div>

  <!-- Bouton "ajouter un drone" -->
  <%= link_to "Add a drone", new_drone_path, class: "btn btn-blue btn-center" %>

<!-- Liste des drones appartenant au logged-in user. Pas de page vu du drone pour l'instant,

la page edit suffit pour les utilisateurs connectés non ?  -->
<div class="container">
  <% current_user.drones.each do |drone| %>
  <div class="row">
    <div class="col-xs-12 drone">
      <div class="drone-image hidden-xs">
      <% if drone.photo_drone? %>
        <%= cl_image_tag drone.photo_drone.path, width: 100, height: 150, crop: :fill %>
        <% else %>
        <%= image_tag "https://www.alain-bensoussan.com/wp-content/uploads/2014/03/Armed-drone%C2%A9-Lee-Barnwell-Fotolia.com_.jpg", class: "drone-image" %>
        <% end %>
      </div>
      <div class= drone-body>
        <h3><%= drone.model %></h3>
        <p><%= drone.description %></p>
      </div>
      <div class="drone-controls">
        <%= link_to "Edit", edit_drone_path(drone), class: "btn btn-blue" %>
      </div>
    </div>
    </div>
    <% end %>
</div>

app/views/pages/home.html.erb
<div class="home-wrapper" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_url "home.jpg" %>');">
  <div class="home-content" style="width: 80%; padding-top: 100px">
  <div class="phrases">
    <h1>Fly there</h1>
    <h2>Rent drones from individuals and <br> experience flying like never before</h2>
    <br>
    </div>
    <div class="form-home">
      <%= render "shared/search" %>
    </div>
  </div>
</div>

app/views/pages/myrentals.html.erb
<div class="tabs1">
  <a class="tab1" href="<%= dashboard_path %>">
    <h3>My drones</h3>
  </a>
  <a class="tab1 active" >
    <h3>My rentals</h3>
  </a>
  <a class="tab1" href="<%= profile_edit_path %>">
    <h3>My account</h3>
  </a>
</div>

<!-- Bouton "ajouter un drone" -->
<%= link_to "Add a drone", new_drone_path, class: "btn btn-blue btn-center" %>

<!-- Liste des drones appartenant au logged-in user. Pas de page vu du drone pour l'instant,
la page edit suffit pour les utilisateurs connectés non ?  -->
<div class="container">
  <% Rental.all.each do |rental| %>
  <div class="row">
    <div class="col-xs-12 drone">
      <!-- ici on est dans le cas du locataire du drone rental.user_id le drone -->
      <% if rental.user_id = current_user %>
      <div class="avatar-category">
        <div class="user-avatar">
         <!-- a utiliser a la place de current_user :rental.drone.user_id.photo.path -->
         <% if rental.drone.user.photo? %>
         <%= cl_image_tag rental.drone.user.photo.path, width: 100, height: 150, crop: :fill %>
         <% else %>
         <%= image_tag "https://api.adorable.io/avatars/285/abott@adorable.png", class: "user-avatar" %>
         <% end %>
         </div>
         <div class="user-name">
         <%= rental.drone.user.first_name %>
        </div>
    </div>
      <div class="drone-image hidden-xs">
      <% if rental.drone.photo_drone? %>
       <%= cl_image_tag rental.drone.photo_drone.path, class: "drone-image" %>
       <% else %>
        <%= image_tag "https://www.alain-bensoussan.com/wp-content/uploads/2014/03/Armed-drone%C2%A9-Lee-Barnwell-Fotolia.com_.jpg", class: "drone-image" %>
        <% end %>
     </div>
     <ul class= "list-inline drone-body">
       <li> <%= rental.drone.model %></li>
       <li><% if rental.drone.available? %>
       <p>Available</p>
       <i class="fa fa-check-circle-o" aria-hidden="true"></i>
       <% end %>
        </li>
       </ul>
     <% end %>
   </div>
 </div>
 <% end %>
</div>