config/routes.rb
Rails.application.routes.draw do

  get 'profile/edit'

  get 'profile/update'

  get 'drones/search', to: 'drones#search'


  resources :drones do
    resources :rentals, only: [ :new, :create ]
  end

  resources :rentals, only: [:destroy, :show]

  get 'dashboard', to: 'pages#dashboard'

  get 'myrentals', to: 'pages#myrentals'


  resources :profile, only: [ :edit, :update ]

  mount Attachinary::Engine => "/attachinary"

  # get 'profile/edit', to: 'profile#edit'

  # patch 'profile/update', to: 'profile#update'

  # get 'rentals/index'

  # get 'rentals/show'

  # get 'rentals/destroy'


  devise_for :users, :controllers => { registrations:  "users/registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/drone.rb
class Drone < ApplicationRecord
  belongs_to :user
  has_many :rentals, dependent: :destroy
  has_attachments :photo_footage, maximum: 3
  has_attachment :photo_drone
end

app/controllers/drones_controller.rb
class DronesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :search, :show ]
  def index
    # possibilité d'un if pour conditionner une selection de l'index
    # en fonction d'un paramettre de recherche
    @drones = Drone.all
  end

  def show
    set_drone
    @rental = Rental.new
    @rental.drone = Drone.find(params[:id])
  end

  def new
    @drone = Drone.new
  end

  def create
    @drone = Drone.new(params_drone_create)
    @drone.user = current_user
    if @drone.save
      redirect_to dashboard_path
    else
      render "drones/new"
    end
  end

  def edit
    @drone = Drone.find(params[:id])
  end

  def update
    @drone = Drone.find(params[:id])
    @drone.update(params_drone_update)
    redirect_to dashboard_path
  end

  def destroy
    @drone = Drone.find(params[:id])
    @drone.destroy

    redirect_to dashboard_path
  end

  def search
    searched_start_date = params[:searched_start_date]
    searched_end_date = params[:searched_end_date]
    @available_drones = available_drones(searched_start_date, searched_end_date)
    @located_users = delete_unlocated_drones(@available_drones)
    @hash = Gmaps4rails.build_markers(@located_users) do |user, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
    end
  end


  private
  def params_drone_create
    params.require(:drone).permit(:brand, :model, :daily_price, :weekly_deal,
                                  :monthly_deal, :autonomy, :range,
                                  :controller, :deposit, :battery, :description,
                                  :photo_drone, photo_footage: [])
  end

  def set_drone
    @drone = Drone.find(params[:id])
  end

  def params_drone_update
    params.require(:drone).permit(:brand, :model, :daily_price, :weekly_deal,
                                  :monthly_deal, :autonomy, :range,
                                  :controller, :deposit, :battery, :available,
                                  :photo_drone, photo_footage: [])
  end

  def available_drones(searched_start_date, searched_end_date)
    return if searched_start_date.nil? || searched_end_date.nil?
    # binding.pry
    rentals = Rental.where.not(start_date: (searched_start_date..searched_end_date))
    rentals = rentals.where.not(end_date: (searched_start_date..searched_end_date))
    drones = []
    rentals.each do |rental|
      drones << rental.drone
    end
    drones.uniq + drone_no_rental
  end

  def drone_no_rental
    drones_no_rental = []
    Drone.all.each do |drone|
      drones_no_rental << drone if drone.rentals == []
    end
    drones_no_rental
  end

  def delete_unlocated_drones(array)
    drones_user = []
    array.each do |drone|
      drones_user << drone.user
    end
    drones_user = drones_user.reject! do |user|
      user.latitude.nil? || user.longitude.nil?
    end
  end
end

app/views/drones/create.html.erb
<h1>Drones#create</h1>
<p>Find me in app/views/drones/create.html.erb</p>

app/views/drones/destroy.html.erb
<h1>Drones#destroy</h1>
<p>Find me in app/views/drones/destroy.html.erb</p>

app/views/drones/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4">

      <%= simple_form_for @drone do |f| %>
      <%= f.error_notification %>
      <%= f.input :brand, required: false, autofocus: true %>
      <%= f.input :model, required: false, autofocus: true %>
      <%= f.input :daily_price, required: false, autofocus: true %>
      <%= f.input :description, required: false, autofocus: true, as: :text %>
      <%= f.input :weekly_deal, required: false, autofocus: true %>
      <%= f.input :monthly_deal, required: false, autofocus: true %>
      <%= f.input :autonomy, required: false, autofocus: true %>
      <%= f.input :range, required: false, autofocus: true %>
      <%= f.input :controller, required: false, autofocus: true %>
      <%= f.input :deposit, required: false, autofocus: true %>
      <%= f.input :battery, required: false, autofocus: true %>
      <%= f.input :available, required: false, autofocus: true %>
      <%= f.input :photo_footage, as: :attachinary %>
      <%= f.input :photo_drone, as: :attachinary %>
      <%= f.submit "Update", class: "btn btn-primary" %>
      <% end %>


      <!-- Bouton de suppression d'un drone-->

      <%= link_to "delete", drone_path(@drone), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>

    </div>
  </div>
</div>

app/views/drones/index.html.erb
<h1>Super l'index</h1>

<!-- # creation des cards de chaque rentals bootstrappées -->
<div class="container">
  <div class="row">
    <% @drones.each do |drone| %>
    <div class="col-xs-12 col-sm-4">
      <div class="drone-card">
        <%= link_to drone_path(drone) do%>
        <!-- # fond des cards et css à définir -->
        <% if drone.photo_drone? %>
        <div class="card-picture" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path drone.photo_drone.path, height: 300, width: 400, crop: :fill %>')">
          <% else %>
          <div class="card-picture" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://petapixel.com/assets/uploads/2017/04/swelpro_feat.jpg');">
            <% end %>
            <div class="card-price">
              <%= drone.daily_price %> € / Jour
            </div>
          </div>
          <div class="card-info">
            <!-- # manque variable user_id.zipcode a activer -->
            <div class="circle-back">
              <div class="card-category center"> <%= drone.user.zip_code %></div>
            </div>
            <div class="card-descript">
              <h2><%= drone.user.first_name %> drone's</h2>
              <p> <%= drone.description %></p>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

app/views/drones/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4">

      <%= simple_form_for @drone do |f| %>
      <%= f.error_notification %>
      <%= f.input :brand, required: false, autofocus: true %>
      <%= f.input :model, required: false, autofocus: true %>
      <%= f.input :daily_price, required: false, autofocus: true %>
      <%= f.input :description, required: false, autofocus: true, as: :text %>
      <%= f.input :weekly_deal, required: false, autofocus: true %>
      <%= f.input :monthly_deal, required: false, autofocus: true %>
      <%= f.input :autonomy, required: false, autofocus: true %>
      <%= f.input :range, required: false, autofocus: true %>
      <%= f.input :controller, required: false, autofocus: true %>
      <%= f.input :deposit, required: false, autofocus: true %>
      <%= f.input :battery, required: false, autofocus: true %>
      <%= f.input :photo_footage, as: :attachinary %>
      <%= f.input :photo_drone, as: :attachinary %>
      <%= f.submit "Create a new drone", class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/drones/search.html.erb
<div class="main-container">
  <div id="map" style="width: 100%; height: 300px;"></div>
<%= render "shared/search" %>

<!-- available drones renvoie un array de drone disponible-->

<% unless @available_drones.nil? %>
<div class="container">
  <div class="row">
    <% @available_drones.each do |drone| %>
    <div class="col-xs-12 col-sm-4">
      <div class="drone-card">
        <%= link_to drone_path(drone) do%>
        <!-- # fond des cards et css à définir -->
        <% if drone.photo_drone? %>
        <div class="card-picture" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path drone.photo_drone.path, height: 300, width: 400, crop: :fill %>')">
          <% else %>
          <div class="card-picture" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://petapixel.com/assets/uploads/2017/04/swelpro_feat.jpg');">
            <% end %>
            <div class="card-price">
              <%= drone.daily_price %> € / Jour
            </div>
          </div>
          <div class="card-info">
            <!-- # manque variable user_id.zipcode a activer -->
            <div class="circle-back">
              <div class="card-category center"> <%= drone.user.zip_code %></div>
            </div>
            <div class="card-descript">
              <h2><%= drone.user.first_name %> drone's</h2>
              <p> <%= drone.description %></p>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <% end %>

</div>




<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/drones/show.html.erb
<!-- # creation d'une vue de un drone bootstrappée integrable dans une card pour le dashboard -->
<div class="show-wrapper" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_url "home.jpg" %>');">
</div>
<div class="container">
  <div class="row">
    <br>
    <% photodrone= %>
    <%  if @drone.photo_drone? %>
    <% cl_image_path @drone.photo_drone.path, height: 150, width: 150, crop: :fill %>
    <% else %>
    <% cl_image_path 'http://csimg-i5.leguide.com/srv/FR/2800902582948/T/150x150/C/FFFFFF/url/mavic-pro-drone-dji.jpg' %>
    <% end %>
    <div class="col-md-8">
      <div class="row">
        <div class="card1">
          <div class="card1-model">
            <h3> <%= @drone.brand %><%= @drone.model %></h3>
            <%= @drone.user.zip_code %> <%= @drone.user.city %>
          </div>
          <div class="card1-photodrone">
            <%= cl_image_tag photodrone %>
          </div>
        </div>

      </div>

      <div class="row">
        <div class="card2">
          <h3>Description</h3>
          <%= @drone.description %>
        </div>
      </div>

      <div class="row">
        <div class="card3">
          <h3>Characteristics</h3><br>
          <ul>
            <li> <strong>Price Day/Week/month </strong>: <%= @drone.daily_price %>€ / <%= @drone.weekly_deal %>€ / <%= @drone.monthly_deal %>€ </li>
            <li> <strong>Brand :</strong> <%= @drone.brand%> </li>
            <li> <strong>Model :</strong> <%= @drone.model%> </li>
            <li> <strong>Range :</strong> <%= @drone.range %> km </li>
            <li> <strong>Time Flight :</strong> <%= @drone.autonomy %> min </li>
            <li> <strong>Number of batteries provided:</strong> <%= @drone.battery %> </li>
            <li> <strong>Need of controller :</strong> <%= @drone.controller ? "Yes" : "No" %> </li>
            <li> <strong>Deposit :</strong> <%= @drone.deposit %>€ </li>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="row">
          <div class="card4">
          <br>
            <h4>Book it !</h4>
            <div> <h3><%= @drone.daily_price %> € per day</h3></div>
            <%= simple_form_for [@drone, @rental], method: :get, url: new_drone_rental_path(@drone) do |f| %>
            <%= f.error_notification message: @drone.errors.messages[:rental].first %>
            <%= f.input :start_date, label: 'From', error: 'La date de debut est obligatoire' %>
            <%= f.input :end_date, label: 'To', error: 'La date de fin est obligatoire' %>
            <%= f.submit "Rent", class: "cta" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/drones/update.html.erb
<h1>Drones#update</h1>
<p>Find me in app/views/drones/update.html.erb</p>